spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/charge_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
